// src/ed/mod.rs
mod buffer_ops;
pub mod build;
mod codeium;
mod command;
mod completion;
mod editing;
mod enter_helper;
mod file_ops;
mod ghost_text;
pub mod git;
pub mod git_commit;
pub mod git_diff;
pub mod git_log;
pub mod git_status;
pub mod goto_def;
mod llm_ext;
mod lsp;
pub mod marks;
mod movement;
mod repeat;
mod replace;
mod ripgrep;
mod search;
mod shortcuts;
pub mod tag;
pub mod text_object;
pub mod visual;
mod window;

pub use buffer_ops::BufferOpsExt;
pub use command::CommandExt;
pub use completion::CompletionExt;
pub use editing::EditingExt;
pub use file_ops::FileOpsExt;
pub use ghost_text::GhostTextExt;
pub use git::{DiffPopup, DiffPopupPrefix, GitExt};
pub use git_commit::GitCommitExt;
pub use git_diff::GitDiffExt;
pub use git_log::GitLogExt;
pub use git_status::GitStatusExt;
pub use goto_def::GotoDefExt;
pub use llm_ext::LlmExt;
pub use lsp::LspExt;
pub use marks::MarksExt;
pub use movement::MovementExt;
pub use repeat::{DeleteDirection, LastAction, RepeatExt, RepeatableAction};
pub use replace::ReplaceExt;
pub use ripgrep::RipgrepExt;
pub use search::SearchExt;
pub use shortcuts::ShortcutsExt;
pub use text_object::{TextObjectExt, TextObjectKind, TextObjectOperator};
pub use visual::{BlockInsertState, VisualExt};
pub use window::WindowExt;
